### ISSUE TITLE
Oculus Go

### ISSUE THREAD

**Issue by vin-ni** [presstube/norman#4]
Hi,
Do you think it's portable to Oculus Go?

Cheers

**Comment by presstube** [comment]
I imagine it might just work out of the box. Want to jump on a google hangout sometime and walk through it together? I don’t have a GO on my end.

**Comment by vin-ni** [comment]
Yeah, let's do that. (I don't have one either but would invest)
When are you available?

**Comment by vin-ni** [comment]
(I'll send you a mail)
